### PR TITLE
fix: fix list-all

### PR DESCRIPTION
**Pull request by bellini666**
I'm having the following issue which this PR should fix:

```python
✔ Select versions to install · kubeseal@latest
/home/bellini/.local/share/rtx/plugins/kubeseal/bin/install: line 53: [: latest: integer expression expected
/home/bellini/.local/share/rtx/plugins/kubeseal/bin/install: line 53: [: latest: integer expression expected
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
/home/bellini/.local/share/rtx/plugins/kubeseal/bin/install: line 53: [: latest: integer expression expected
/home/bellini/.local/share/rtx/plugins/kubeseal/bin/install: line 53: [: latest: integer expression expected
Downloading kubeseal from https://github.com/bitnami-labs/sealed-secrets/releases/download/vlatest/kubeseal-latest-linux-amd64.tar.gz to /tmp/kubeseal_vcvdg0/kubeseal-latest-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
rtx kubeseal@latest Downloading kubeseal from https://github.com/bitnami-labs/sealed-secrets/releases/download/vlatest/kubeseal-latest-linux-amd64.tar.gz to /tmp/kubeseal_vcvdg0/kubeseal-latest-linux-amd64.tar.gz                     ✗ 0s rtx ~/.local/share/rtx/plugins/kubeseal/bin/install exited with non-zero status: exit code 22
rtx Run with RTX_DEBUG=1 for more information
```

### CODE REVIEW

**Comment by bellini666** [comment]
@stefansedich ping

**Review by stefansedich — APPROVED** [review]
LGTM

**Comment by stefansedich** [comment]
Wow 6 months... I'm sorry I had missed this.

**Comment by bellini666** [comment]
> Wow 6 months... I'm sorry I had missed this.

hahaha it happens :)

**Pull request merged**
